SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS users(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,
 role ENUM('user','admin') NOT NULL DEFAULT 'user',status ENUM('active','disabled') NOT NULL DEFAULT 'active',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS projects(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,owner_id BIGINT UNSIGNED NOT NULL,name VARCHAR(160) NOT NULL,base_url VARCHAR(500) NOT NULL,
 share_token VARCHAR(80) NOT NULL UNIQUE,share_password_hash VARCHAR(255) NULL,status ENUM('active','archived') NOT NULL DEFAULT 'active',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_projects_owner FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE CASCADE,INDEX idx_projects_owner(owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS project_members(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,project_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,role ENUM('developer','reviewer','viewer') NOT NULL DEFAULT 'viewer',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uniq_project_user(project_id,user_id),
 CONSTRAINT fk_pm_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,CONSTRAINT fk_pm_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS pages(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,project_id BIGINT UNSIGNED NOT NULL,title VARCHAR(190) NULL,url VARCHAR(700) NOT NULL,status ENUM('active','hidden') NOT NULL DEFAULT 'active',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uniq_project_url(project_id,url(250)),CONSTRAINT fk_pages_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,INDEX idx_pages_project(project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS captures(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,page_id BIGINT UNSIGNED NOT NULL,file_path VARCHAR(500) NOT NULL,width INT UNSIGNED NOT NULL DEFAULT 0,height INT UNSIGNED NOT NULL DEFAULT 0,
 source ENUM('pagespeed','thumio','upload') NOT NULL DEFAULT 'upload',created_by BIGINT UNSIGNED NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_captures_page FOREIGN KEY(page_id) REFERENCES pages(id) ON DELETE CASCADE,CONSTRAINT fk_captures_user FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,INDEX idx_captures_page(page_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS annotations(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,capture_id BIGINT UNSIGNED NOT NULL,created_by BIGINT UNSIGNED NULL,number INT UNSIGNED NOT NULL,
 x_pct DECIMAL(7,4) NOT NULL,y_pct DECIMAL(7,4) NOT NULL,w_pct DECIMAL(7,4) NOT NULL,h_pct DECIMAL(7,4) NOT NULL,
 title VARCHAR(190) NOT NULL,description TEXT NULL,requested_text TEXT NULL,target_url VARCHAR(700) NULL,
 status ENUM('open','in_progress','need_clarification','done','approved','reopened') NOT NULL DEFAULT 'open',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_ann_capture FOREIGN KEY(capture_id) REFERENCES captures(id) ON DELETE CASCADE,CONSTRAINT fk_ann_user FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 UNIQUE KEY uniq_capture_number(capture_id,number),INDEX idx_ann_capture_status(capture_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS comments(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,annotation_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NULL,guest_name VARCHAR(120) NULL,parent_id BIGINT UNSIGNED NULL,body TEXT NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_comments_annotation FOREIGN KEY(annotation_id) REFERENCES annotations(id) ON DELETE CASCADE,CONSTRAINT fk_comments_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,CONSTRAINT fk_comments_parent FOREIGN KEY(parent_id) REFERENCES comments(id) ON DELETE CASCADE,INDEX idx_comments_annotation(annotation_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS attachments(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,annotation_id BIGINT UNSIGNED NOT NULL,original_name VARCHAR(190) NOT NULL,file_path VARCHAR(500) NOT NULL,mime_type VARCHAR(100) NOT NULL,file_size INT UNSIGNED NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_attachments_annotation FOREIGN KEY(annotation_id) REFERENCES annotations(id) ON DELETE CASCADE,INDEX idx_attachments_annotation(annotation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS activity(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,project_id BIGINT UNSIGNED NOT NULL,actor_user_id BIGINT UNSIGNED NULL,action VARCHAR(80) NOT NULL,entity_type VARCHAR(60) NOT NULL,entity_id BIGINT UNSIGNED NULL,meta_json TEXT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_activity_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,CONSTRAINT fk_activity_user FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL,INDEX idx_activity_project(project_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS=1;
